<?php

return array(
    "recent" => 10,
    "types" => array(
        "exhibition" => array(
            "title" => "Выставки и экспозиции",
            "model" => "App_Models_Exhibition",
            "public_list" => "/exhibitions",
            "view_link" => "/exhibitions/{id}",
            "boolean" => array("published", "closed"),
            "tab" => "exhibitions",
            ),
        "object" => array(
            "title" => "Экспонаты",
            "model" => "App_Models_Object",
            "public_list" => "/objects",
            "view_link" => "/objects/{id}",
            "boolean" => array("published"),
            "list_where" => "`published` = 1 ORDER BY `id` DESC",
            "template_list" => "objects.twig",
            "template_item" => "object.twig",
            ),
        "excursion" => array(
            "boolean" => array("published"),
            "list_where" => "published = 1 ORDER BY `order`, title",
            "admin_list_where" => "1 ORDER BY `order`, title",
            "model" => "App_Models_Excursion",
            "public_list" => "/excursions",
            "template_item" => "excursion.twig",
            "template_list" => "excursions.twig",
            "admin_list_template" => "excursion-admin-list.twig",
            "title" => "Экскурсии",
            "view_link" => "/excursions/{id}",
            "tab" => "excursions",
            ),
        "event" => array(
            "boolean" => array("published"),
            "list_where" => "published = 1 ORDER BY `date` DESC, `time`",
            "model" => "App_Models_Event",
            "public_list" => "/events",
            "template_item" => "event.twig",
            "template_list" => "events.twig",
            "title" => "События",
            "edit_subtitle" => "Здесь следует публиковать информацию о событиях, связанных с музеем, которые могут посетить люди.  Это приглашение на мероприятие.  Размещать здесь информацию о внутренних коммандировках, тем более — задним числом, не надо: в этом нет никакого смысла, посетителям это ничего не даёт.",
            "view_link" => "/events/{id}",
            ),
        "article" => array(
            "boolean" => array("published"),
            "list_where" => "`published` = 1 ORDER BY `title`",
            "model" => "App_Models_Article",
            "public_list" => "/articles",
            "template_item" => "article.twig",
            "template_list" => "articles.twig",
            "title" => "Статьи",
            "view_link" => "/articles/{id}",
            ),
        "place" => array(
            "title" => "Места",
            "boolean" => array("published"),
            "list_where" => "`published` = 1 ORDER BY `id`",
            "model" => "App_Models_Place",
            "public_list" => "/places",
            "tab" => "places",
            ),
        "archive" => array(
            "title" => "Архивные документы",
            "boolean" => array("published"),
            "list_where" => "`published` = 1 ORDER BY `date` DESC",
            "model" => "App_Models_Archive",
            "public_list" => "/archive",
            "tab" => "archive",
            ),
        "blog" => array(
            "title" => "Дневник",
            "boolean" => array("published"),
            "list_where" => "`published` = 1 ORDER BY `date` DESC",
            "model" => "App_Models_Blog",
            "public_list" => "/blog",
            "tab" => "blog",
            ),
        "splash" => array(
            "title" => "Заставки",
            "subtitle" => "Заставки — это большие картинки с подписями и ссылками.  Они видны на главной странице.  Они привлекают внимание к основным действующим экспозициям и интересным объектам.",
            "model" => "App_Models_Splash",
            "admin_list_template" => "splash-admin-list.twig",
            ),
        "file" => array(
            "title" => "Файлы",
            "subtitle" => "Здесь можно загружать картинки для использования в текстах.",
            "model" => "App_Models_File",
            "can_add" => false,
            "dashboard" => false,
            ),
        "photo" => array(
            "title" => "Фотографии",
            "model" => "App_Models_Photo",
            "can_add" => false,
            "dashboard" => true,
            "admin_list_template" => "photos-admin.twig",
            "public_list" => "/photo",
            "view_link" => "/photo/{id}",
            "boolean" => array("published"),
            "tab" => "photo",
            ),
        ),
    );
